// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6m7nzl3T3ZOKdY4gqiBvCaMg0M3HI7CU',
    appId: '1:371130025900:web:25d33c2f4a52efb6af9c09',
    messagingSenderId: '371130025900',
    projectId: 'crudtutorial-759fd',
    authDomain: 'crudtutorial-759fd.firebaseapp.com',
    storageBucket: 'crudtutorial-759fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCime1doSqjEZTb6VOYYeUHcCO37_KrPoA',
    appId: '1:371130025900:android:6892994971dfddb8af9c09',
    messagingSenderId: '371130025900',
    projectId: 'crudtutorial-759fd',
    storageBucket: 'crudtutorial-759fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iyR4jdo7vmVBuq2uP9iPbms6_pfpuSY',
    appId: '1:371130025900:ios:d81e8bf7e67c4788af9c09',
    messagingSenderId: '371130025900',
    projectId: 'crudtutorial-759fd',
    storageBucket: 'crudtutorial-759fd.appspot.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iyR4jdo7vmVBuq2uP9iPbms6_pfpuSY',
    appId: '1:371130025900:ios:d81e8bf7e67c4788af9c09',
    messagingSenderId: '371130025900',
    projectId: 'crudtutorial-759fd',
    storageBucket: 'crudtutorial-759fd.appspot.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6m7nzl3T3ZOKdY4gqiBvCaMg0M3HI7CU',
    appId: '1:371130025900:web:e73baa32c646ab29af9c09',
    messagingSenderId: '371130025900',
    projectId: 'crudtutorial-759fd',
    authDomain: 'crudtutorial-759fd.firebaseapp.com',
    storageBucket: 'crudtutorial-759fd.appspot.com',
  );
}
